export const words = [
    "world", "chat", "poisson", "chaise", "tablier", "bonjour", "tiroir", "table",
    "maison", "livre", "ordinateur", "fenêtre", "porte", "vélo", "arbre", "fleur",
    "soleil", "lune", "étoile", "nuage", "pluie", "neige", "vent", "montagne",
    "rivière", "lac", "forêt", "prairie", "désert", "île", "océan", "mer",
    "sable", "rocher", "sentier", "chemin", "pont", "ville", "village", "rue",
    "place", "marché", "école", "université", "bibliothèque", "hôpital", "pharmacie",
    "restaurant", "café", "boulangerie", "boucherie", "fromagerie", "parc",
    "jardin", "musée", "théâtre", "cinéma", "stade", "gare", "aéroport",
    "bus", "tramway", "métro", "taxi", "voiture", "moto", "camion", "bateau",
    "avion", "hélicoptère", "train", "vélo", "scooter", "ballon", "jeu", "sport",
    "football", "basketball", "tennis", "rugby", "natation", "course", "gymnastique",
    "danse", "musique", "chanson", "instrument", "peinture", "sculpture", "photographie",
    "cinéma", "livre", "roman", "poésie", "théâtre", "magazine", "journal", "article",
    "histoire", "géographie", "mathématiques", "physique", "chimie", "biologie",
    "informatique", "langue", "anglais", "espagnol", "allemand", "italien", "russe",
    "chinois", "japonais", "arabe", "portugais", "grec", "latin", "français", "culture",
    "tradition", "cuisine", "recette", "ingrédient", "saveur", "goût", "odeur",
    "texture", "couleur", "forme", "taille", "poids", "âge", "temps", "année",
    "mois", "semaine", "jour", "heure", "minute", "seconde", "moment", "événement",
    "situation", "activité", "travail", "emploi", "carrière", "entreprise", "bureau",
    "collègue", "patron", "salaire", "contrat","oiseau", "papillon", "fourmi", "abeille", "souris", "éléphant", "girafe",
  "zèbre", "lion", "tigre", "cheval", "vache", "mouton", "cochon", "canard",
  "poule", "dinde", "singe", "renard", "loup", "serpent", "grenouille",
  "tortue", "crocodile", "hippopotame", "kangourou", "panda", "ours",
  "raton-laveur", "chauve-souris", "papillon", "libellule", "coccinelle",
  "mouche", "guêpe", "araignée", "mille-pattes", "escargot", "limace",
  "bison", "buffalo", "daim", "cerf", "chevreuil", "lynx", "panthère",
  "chameau", "dromadaire", "oryx", "gazelle", "antilope", "putois",
  "blaireau", "hibou", "faucon", "aigle", "corbeau", "merle", "rouge-gorge",
  "pigeon", "perroquet", "colibri", "flamant", "pingouin", "manchot",
  "cigogne", "pélican", "hirondelle", "buse", "canari", "tourterelle",
  "mésange", "geai", "pie", "star", "albatros", "cormoran", "frelon",
  "sauterelle", "cigale", "scarabée", "fourmilier", "termite", "sauterelle",
  "coccinelle", "luciole", "moustique", "taureau", "veau", "porc-épic",
  "hippocampe", "écrevisse", "homard", "crevette", "moules", "huître",
  "calamar", "pieuvre", "langouste", "barbeau", "concombre", "tomate",
  "carotte", "pomme", "banane", "orange", "fraise", "cerise", "raisin",
  "pêche", "abricot", "mangue", "ananas", "kiwi", "melon", "pastèque",
  "citron", "lime", "pamplemousse", "prune", "noix", "amande", "noisette",
  "cacahuète", "pistache", "châtaigne", "grenade", "figue", "datte",
  "mûre", "framboise", "myrtille", "groseille", "kiwano", "lychee",
  "papaye", "persimmon", "tamarin", "vanille", "gingembre", "curcuma",
  "cannelle", "basilic", "menthe", "thym", "romarin", "coriandre",
  "persil", "aneth", "origan", "sauge", "lavande", "camomille", "mélisse",
  "fenouil", "cresson", "laitue", "épinard", "chou", "brocoli", "courgette",
  "aubergine", "poivron", "panais", "betterave", "radis",
  "céleri", "asperge", "artichaut", "champignon", "truffe", "tofu",
  "tempeh", "seitan", "quinoa", "sarrasin", "orge", "avoine", "riz",
  "blé", "épeautre", "millet", "maïs", "amarante", "farro", "bulgur",
  "couscous", "polenta", "griocereals", "sorgho", "tapioca", "manioc",
  "patate", "igname", "topinambour", "salsifis", "chou-fleur", "piment",
  "betterave", "navet", "Bruxelles", "radis noir", "céleri",
  "chicorée", "endive", "bette", "roquette", "cresson", "pissenlit",
  "artichaut", "cardon", "fenouil", "lentille", "haricot",
  "fève", "edamame", "tofu", "tempeh", "seitan", "quinoa", "amarante",
  "sarrasin", "millet", "épeautre", "kamut", "triticale", "orzo", "farro",
  "spelt", "teff", "kamut", "bulgur", "couscous", "polenta", "griocereals",
  "sorgho", "tapioca", "manioc", "arrow-root",

  ];